name: Build Release ZIPs

on:
  push:
    tags:
      - "v*.*.*"


jobs:
  build-windows:
    name: Build Windows ZIPs
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build standard release
        run: ./gradlew distZip
      - name: Upload standard release
        uses: actions/upload-artifact@v2
        with:
          name: OpenSR Launchpad ${{github.ref_name}} (Standard-Windows).zip
          path: build/distributions/OpenStarRuler-Launchpad.zip

      - name: Build standalone release
        run: ./gradlew jlink
      - name: Create standalone launcher
        run: '"cd bin && OSRLaunchpad.bat" | Out-File -FilePath OpenStarRuler-Launchpad\OSRLauncher.bat -Encoding "ascii"'
        shell: powershell
      - name: Pack standalone release
        run: New-Item -Name "OpenStarRuler-Launchpad" -ItemType "directory"; Rename-Item README.md README.txt; Copy-Item -Path README.txt,LICENSE.txt,build/image/*,OSRLaunchpad.bat -Destination "OpenStarRuler-Launchpad" -Recurse; Compress-Archive -Path "OpenStarRuler-Launchpad" -DestinationPath "standalone-windows.zip"
        shell: powershell
      - name: Upload standalone release
        uses: actions/upload-artifact@v2
        with:
          name: OpenSR Launchpad ${{github.ref_name}} (Standalone-Win64).zip
          path: standalone-windows.zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: adopt
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Build standard release
        run: ./gradlew distZip
      - name: Upload standard release
        uses: actions/upload-artifact@v2
        with:
          name: OpenSR Launchpad ${{github.ref_name}} (Standard-Linux).zip
          path: build/distributions/OpenStarRuler-Launchpad.zip

      # TODO: Figure out launcher script (and whether one is even needed)
      #- name: Build standalone release
      #  run: ./gradlew jlink

  deploy:
    name: Attach ZIPs to release
    needs:
      - build-windows
      - build-linux
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Attach artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: '**/OpenSR Launchpad*.zip'
          fail_on_unmatched_files: true